[project]
channels = ["conda-forge"]
name = "autoServer"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"

[pypi-dependencies]
ovh = ">=1.2.0, <2"
pyyaml = ">=6.0.2, <7"
